#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : python-magnumclient
Version  : 2.3.0
Release  : 15
URL      : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.3.0.tar.gz
Source0  : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.3.0.tar.gz
Source99 : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.3.0.tar.gz.asc
Summary  : Client library for Magnum API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-magnumclient-bin
Requires: python-magnumclient-python
Requires: Babel
Requires: cryptography
Requires: decorator
Requires: keystoneauth1
Requires: os-client-config
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Python bindings to the Magnum API
=================================
.. image:: https://img.shields.io/pypi/v/python-magnumclient.svg
:target: https://pypi.python.org/pypi/python-magnumclient/
:alt: Latest Version

%package bin
Summary: bin components for the python-magnumclient package.
Group: Binaries

%description bin
bin components for the python-magnumclient package.


%package python
Summary: python components for the python-magnumclient package.
Group: Default

%description python
python components for the python-magnumclient package.


%prep
%setup -q -n python-magnumclient-2.3.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489334189
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489334189
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/magnum

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
