#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-magnumclient
Version  : 2.0.0
Release  : 8
URL      : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.0.0.tar.gz
Source0  : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.0.0.tar.gz
Summary  : Client library for Magnum API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-magnumclient-bin
Requires: python-magnumclient-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : msgpack-python-python
BuildRequires : os-client-config-python
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : positional-python
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pyrsistent-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : virtualenv
Patch1: 0001-Enable-python3-support.patch

%description
Python bindings to the Magnum API
=================================
.. image:: https://img.shields.io/pypi/v/python-magnumclient.svg
:target: https://pypi.python.org/pypi/python-magnumclient/
:alt: Latest Version

%package bin
Summary: bin components for the python-magnumclient package.
Group: Binaries

%description bin
bin components for the python-magnumclient package.


%package python
Summary: python components for the python-magnumclient package.
Group: Default
Requires: os-client-config-python
Requires: oslo.serialization-python
Requires: oslo.utils-python
Requires: prettytable

%description python
python components for the python-magnumclient package.


%prep
%setup -q -n python-magnumclient-2.0.0
%patch1 -p1

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/magnum

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
