#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-magnumclient
Version  : 2.0.0
Release  : 4
URL      : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.0.0.tar.gz
Source0  : http://tarballs.openstack.org/python-magnumclient/python-magnumclient-2.0.0.tar.gz
Summary  : Client library for Magnum API
Group    : Development/Tools
License  : Apache-2.0
Requires: python-magnumclient-bin
Requires: python-magnumclient-python
BuildRequires : Jinja2
BuildRequires : PyYAML-python
BuildRequires : Sphinx-python
BuildRequires : coverage-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : funcsigs-python
BuildRequires : hacking-python
BuildRequires : iso8601-python
BuildRequires : msgpack-python-python
BuildRequires : netifaces-python
BuildRequires : oslo.config
BuildRequires : oslo.serialization-python
BuildRequires : oslo.utils-python
BuildRequires : oslosphinx-python
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : prettytable
BuildRequires : pyrsistent-python
BuildRequires : python-dev
BuildRequires : python-keystoneclient-python
BuildRequires : python-mimeparse-python
BuildRequires : python-mock-python
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : stevedore
BuildRequires : subunit
BuildRequires : testrepository-python
BuildRequires : testscenarios
BuildRequires : testtools
BuildRequires : testtools-python
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : wrapt-python

%description
Python bindings to the Magnum API
=================================
.. image:: https://img.shields.io/pypi/v/python-magnumclient.svg
:target: https://pypi.python.org/pypi/python-magnumclient/
:alt: Latest Version

%package bin
Summary: bin components for the python-magnumclient package.
Group: Binaries

%description bin
bin components for the python-magnumclient package.


%package python
Summary: python components for the python-magnumclient package.
Group: Default
Requires: oslo.serialization-python
Requires: oslo.utils-python
Requires: prettytable
Requires: requests-python
Requires: six-python
Requires: stevedore

%description python
python components for the python-magnumclient package.


%prep
%setup -q -n python-magnumclient-2.0.0

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/magnum

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
